### ISSUE TITLE
些細なコードの修正案

### ISSUE THREAD

**Issue by monkukui** [HUITGroup/member-bot#4]
### ここに continue いらない
- https://github.com/HUITGroup/member-bot/blob/main/batch.go#L90
- https://github.com/HUITGroup/member-bot/blob/main/batch.go#L108
- https://github.com/HUITGroup/member-bot/blob/main/batch.go#L110

### 意味のないコメント
- https://github.com/HUITGroup/member-bot/blob/main/join.go#L24

**Comment by shoumoji** [comment]
https://github.com/HUITGroup/member-bot/pull/5

で移行するときに合わせて修正しました。
